--pretty
--pager=no
--infer-market-prices
--infer-costs

[balance]            --layout=bare --tree --depth 3
[balancesheet]       --layout=bare --tree --depth 3
[balancesheetequity] --layout=bare --tree --depth 3
[cashflow]           --layout=bare --tree --depth 3
[incomestatement]    --layout=bare --tree --depth 3
