--pretty
--pager=no
--infer-market-prices
--infer-costs
cur:PHP

[balance]            --layout=bare --tree --depth 5
[balancesheet]       --layout=bare --tree --depth 5
[balancesheetequity] --layout=bare --tree --depth 3
[cashflow]           --layout=bare --tree --depth 3
[incomestatement]    --layout=bare --tree --depth 3
